name: Main
on: 
  push: 
    tags:
      - "v*.*.*"
jobs: 
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Echo Version
        run: echo ${{ steps.get_version.outputs.VERSION }}
      - name: Echo App
        run : ls -la

      - name: ZIP
        run: zip -r playerLastPlay-${{ steps.get_version.outputs.VERSION }}.zip ./ -x './.gitignore' -x './.github/*' -x './.git/*' -x '*.DS_Store'

      - name: MCDR
        run: mv playerLastPlay-${{ steps.get_version.outputs.VERSION }}.zip playerLastPlay-${{ steps.get_version.outputs.VERSION }}.mcdr

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with: 
          name: playerLastPlay-${{ steps.get_version.outputs.VERSION }}.mcdr
          path: ./playerLastPlay-${{ steps.get_version.outputs.VERSION }}.mcdr
          
      - name: Upload to Github release
        uses: softprops/action-gh-release@v1
        with:
          files: playerLastPlay-${{ steps.get_version.outputs.VERSION }}.mcdr
          tag_name: ${{ steps.get_version.outputs.VERSION }}

      

          

